### ISSUE TITLE
为什么我使用这个项目，小电影和无聊图都是没有显示数据的呢?

### ISSUE THREAD

**Issue by whyalwaysmea** [ZhaoKaiQiang/JianDan#18]

**Comment by ZhaoKaiQiang** [comment]
数据接口偶尔不稳定，另外网络情况不好时，会出现连接超时现象

**Comment by whyalwaysmea** [comment]
好的，还有一点不明白。为什么在MainActivity中要调用onConfigurationChanged();我记忆中需要在AndroidManifest.xml配置了相关的android:configChanges才会回调该函数，
