### ISSUE TITLE
更新material-dialogs到0.7.3.1到最新才编译好

### ISSUE THREAD

**Issue by itxuye** [ZhaoKaiQiang/JianDan#9]
凯子哥，我是重新下载调试你的煎蛋客户端，一开始就显示无法加载material-dialogs为依赖，我想你是以前有用的，三天前这个material-dialogs更新了。我不清楚我的0.7.2.0为什么down不下来。或许其他人没问题。

**Comment by ZhaoKaiQiang** [comment]
已更新到最新版本依赖
